---
# install and setup NRPE and checks

- name: Check Operating System
  ansible.builtin.fail:
    msg: "You're not running a supported operating system (CentOS, RHEL 7+, Rocky, Fedora, Debian, Ubuntu, or FreeBSD)"
  when:
    - ansible_os_family not in ["RedHat", "Rocky", "Debian", "FreeBSD"]

- name: Install gnupg2 (Legacy EL7)
  ansible.builtin.package:
    name: gnupg2
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int == 7

- name: Install gnupg2
  ansible.builtin.dnf:
    name: gnupg2
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 8

- name: Import EPEL GPG Key
  ansible.builtin.rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int in [7, 8, 9, 10]

- name: Install EPEL repo (EL7)
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int == 7

- name: Install EPEL repo (EL8+)
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int in [8, 9, 10]

- name: Install Python3 for Fedora/EL8+ minimal clients
  ansible.builtin.dnf:
    name: python3
    state: present
  become: true
  when:
    - ansible_os_family in ["RedHat", "Rocky"]
    - ansible_distribution_major_version | int >= 8
    - ansible_system == "Linux"

- name: Symlink Python to Python3 for EL8/Fedora
  ansible.builtin.file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  when:
    - ansible_os_family in ["RedHat", "Rocky"]
    - ansible_distribution_major_version | int >= 8
    - ansible_python_version is version('3.6', '<')
    - ansible_system == "Linux"
  ignore_errors: true

- name: Install NRPE and Common Plugins (EL7)
  ansible.builtin.yum:
    name:
      - nrpe
      - nagios-plugins-load
      - nagios-plugins-uptime
      - nagios-plugins-swap
      - nagios-plugins-procs
      - nagios-plugins-users
      - nagios-plugins-disk
      - nagios-plugins-tcp
      - nagios-plugins-file_age
    state: present
  become: true
  when:
    - ansible_distribution_major_version | int <= 7
    - ansible_os_family == "RedHat"

- name: Install NRPE and Common Plugins (EL8+)
  ansible.builtin.dnf:
    name:
      - nrpe
      - nagios-plugins-load
      - nagios-plugins-uptime
      - nagios-plugins-swap
      - nagios-plugins-procs
      - nagios-plugins-users
      - nagios-plugins-disk
      - nagios-plugins-tcp
      - nagios-plugins-file_age
    state: present
  become: true
  when:
    - ansible_distribution_major_version | int >= 8
    - ansible_os_family == "RedHat"

- name: Install NRPE and Common Plugins (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - nagios-nrpe-server
      - monitoring-plugins
      - nagios-plugins-contrib
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Check if BSD ports structure exists
  ansible.builtin.stat:
    path: /usr/ports/net-mgmt/nagios-plugins/distinfo
  when: ansible_system == "FreeBSD"
  register: bsd_ports_structure
  ignore_errors: true

- name: Fetch new BSD ports tree, this might take a while.
  ansible.builtin.command: portsnap auto
  become: true
  when:
    - ansible_system == "FreeBSD"
    - bsd_ports_structure.stat.exists is defined
    - bsd_ports_structure.stat.exists
  changed_when: true

- name: Install NRPE and Common Plugins for FreeBSD, this might take a while.
  community.general.pkgng:
    name:
      - nrpe3
      - nagios-plugins
  become: true
  when: ansible_system == "FreeBSD"

- name: Install libsemanage-python (EL7)
  ansible.builtin.yum:
    name: libsemanage-python
    state: present
  become: true
  when:
    - ansible_distribution_major_version | int <= 7
    - ansible_os_family == "RedHat"
  ignore_errors: true

- name: Set Fact for Root Disk
  ansible.builtin.set_fact:
    host_root_disk: "{{ ansible_mounts | json_query(query) }}"
  vars:
    query: "[?mount=='/'].device"

- name: Setup NRPE client configuration
  ansible.builtin.template:
    src: nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
    force: true
  become: true
  when: ansible_system == "Linux"

- name: Setup NRPE client configuration on FreeBSD
  ansible.builtin.template:
    src: nrpe.cfg.j2
    dest: /usr/local/etc/nrpe.cfg
    force: true
  become: true
  when: ansible_system == "FreeBSD"

- name: Copy mdadm check_raid plugin (RedHat/Rocky)
  ansible.builtin.copy:
    src: check_raid
    dest: /usr/lib64/nagios/plugins/check_raid
    mode: '0755'
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_os_family in ["RedHat", "Rocky"]

- name: Copy mdadm check_raid plugin (Debian/Ubuntu)
  ansible.builtin.copy:
    src: check_raid
    dest: /usr/lib/nagios/plugins/check_raid
    mode: '0755'
  become: true
  when: ansible_os_family == "Debian"

- name: Copy uptime check tool for FreeBSD
  ansible.builtin.copy:
    src: bsd_check_uptime.sh
    dest: /usr/local/libexec/nagios/bsd_check_uptime
    mode: '0755'
  become: true
  when: ansible_system == "FreeBSD"

- name: Apply SELinux boolean nagios_run_sudo
  ansible.posix.seboolean:
    name: nagios_run_sudo
    state: true
    persistent: true
  ignore_errors: true
  when:
    - ansible_distribution_major_version | int <= 7
    - ansible_os_family == "RedHat"
  become: true

- name: Apply SELinux boolean logging_syslogd_run_nagios_plugins
  ansible.posix.seboolean:
    name: logging_syslogd_run_nagios_plugins
    state: true
    persistent: true
  ignore_errors: true
  when:
    - ansible_distribution_major_version | int <= 7
    - ansible_os_family == "RedHat"
  become: true

- name: Enable and Restart NRPE service (RedHat/Rocky 7+)
  ansible.builtin.service:
    name: nrpe
    state: restarted
    enabled: true
  become: true
  when:
    - ansible_distribution_major_version | default(0) | int >= 7
    - ansible_os_family in ["RedHat", "Rocky"]

- name: Enable and Restart NRPE service (Debian/Ubuntu)
  ansible.builtin.service:
    name: nagios-nrpe-server
    state: restarted
    enabled: true
  become: true
  when: ansible_os_family == "Debian"

- name: Enable NRPE service on FreeBSD
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: nrpe3_enable="YES"
    state: present
    backup: true
  when: ansible_system == "FreeBSD"

- name: Start NRPE service on FreeBSD
  ansible.builtin.service:
    name: nrpe3
    enabled: true
    state: restarted
  when: ansible_system == "FreeBSD"

- name: Enable and Restart NRPE service (EL6)
  ansible.builtin.service:
    name: nrpe
    state: restarted
    enabled: true
  become: true
  when:
    - ansible_distribution_major_version | default(0) | int <= 6
    - ansible_os_family == "RedHat"
