---
- name: save iptables
  ansible.builtin.shell: iptables-save > /etc/sysconfig/iptables
  become: true
  when: ansible_os_family in ["RedHat", "Rocky"]

- name: save iptables debian
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  become: true
  when: ansible_os_family == "Debian"
  listen: save iptables
